### ISSUE TITLE
日付のフォーマット処理

### ISSUE THREAD

**Issue by ishi720** [ishi720/qiita_api_sample#21]

**Comment by ishi720** [comment]
更新日時が
2024-06-24T01:11:52+09:00
となってしまっているため、修正したい

**Comment by mizu0830** [comment]
SampleCode
```Python
from datetime import datetime

# 与えられた更新日時の文字列
original_date_str = "2024-06-24T01:11:52+09:00"

# datetimeオブジェクトに変換する
original_date = datetime.fromisoformat(original_date_str)

# 新しいフォーマットで日付を文字列に変換する
new_date_str = original_date.strftime("%Y-%m-%d(%a) %H:%M:%S")

print(new_date_str)  # 出力例: 2024-06-24 01:11:52
```

**Comment by mizu0830** [comment]
日付のフォーマットの一般的な指定方法
以下は、主要な日付フォーマット指定子の例です。これらを組み合わせて使うことで、必要な形式に日付を整形することができます。

年

%Y: 4桁の西暦年 (例: 2023)
%y: 2桁の西暦年 (例: 23)
月

%m: 0埋めされた月 (01 - 12)
%B: 完全な月の名前 (例: January)
%bまたは%h: 略称された月の名前 (例: Jan)
日

%d: 0埋めされた日 (01 - 31)
曜日

%A: 完全な曜日の名前 (例: Monday)
%a: 略称された曜日の名前 (例: Mon)
時刻

%H: 24時間形式の時 (00 - 23)
%I: 12時間形式の時 (01 - 12)
%M: 分 (00 - 59)
%S: 秒 (00 - 59)
%p: AM/PMを表す (例: AM)
その他

%Z: タイムゾーンの名前 (例: UTC, GMT, JST)

**Comment by ishi720** [comment]
#32 日付のフォーマット処理の実装

**Comment by ishi720** [comment]
ありがとうございましたー
